// <auto-generated />
using MarInTime.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarInTime.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20251225192634_ChangeDecimalForCoordinatesToDouble")]
    partial class ChangeDecimalForCoordinatesToDouble
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarInTime.Domain.Entities.Country", b =>
                {
                    b.Property<string>("IsoId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IsoId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("MarInTime.Domain.Entities.Port", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CountryId")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "CountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("MarInTime.Domain.Entities.Route", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("PortRoute", b =>
                {
                    b.Property<byte>("RoutesId")
                        .HasColumnType("smallint");

                    b.Property<string>("PortsId")
                        .HasColumnType("text");

                    b.Property<string>("PortsCountryId")
                        .HasColumnType("text");

                    b.HasKey("RoutesId", "PortsId", "PortsCountryId");

                    b.HasIndex("PortsId", "PortsCountryId");

                    b.ToTable("PortRoute");
                });

            modelBuilder.Entity("MarInTime.Domain.Entities.Port", b =>
                {
                    b.HasOne("MarInTime.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PortRoute", b =>
                {
                    b.HasOne("MarInTime.Domain.Entities.Route", null)
                        .WithMany()
                        .HasForeignKey("RoutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarInTime.Domain.Entities.Port", null)
                        .WithMany()
                        .HasForeignKey("PortsId", "PortsCountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
